name: xeus-octave
channels:
  - conda-forge
dependencies:
  - xeus-octave==0.1.0-h7024898_5.conda
  # For Plotly graphical toolkit
  - plotly
  # Runtime dependency for Octave ``symbolic`` package.
  - sympy
  # For compiling the Octave ``control`` and ``signal`` packages
  - compilers
  - make



